# Docs: https://fly.io/docs/reference/configuration/

app = "readclip"
primary_region = "sin"

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 8080
  protocol = "tcp"
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
